### PR TITLE
Convert blacklist, theme, utils and Button component to TypeScript

### PR DESCRIPTION
**Pull request by LucianBuzzo**
change-type: patch

### CODE REVIEW

**Comment by thgreasi** [comment]
@LucianBuzzo could we proceed and merge this?

**Comment by LucianBuzzo** [comment]
@thgreasi If possible, I want to wait for this PR to got through first --> https://github.com/resin-io-modules/resin-components/pull/193

**Comment by thgreasi** [comment]
Would love to see that merged at some point :) no pressure though

**Comment by LucianBuzzo** [comment]
@thgreasi Yep this can get merged now

**Pull request merged**
